//
// Generated file, do not edit! Created by opp_msgtool 6.1 from src/EdgeNode/OBS_BurstifierInfo.msg.
//

#ifndef __OBS_BURSTIFIERINFO_M_H
#define __OBS_BURSTIFIERINFO_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class OBS_BurstifierInfo;
/**
 * Class generated from <tt>src/EdgeNode/OBS_BurstifierInfo.msg:23</tt> by opp_msgtool.
 * <pre>
 * // Additional burst control info included in OBS_PacketBurstifier and OBS_FileBurstifier.
 * class OBS_BurstifierInfo extends cObject
 * {
 *     int label = -1; // Destination label.
 * }
 * </pre>
 */
class OBS_BurstifierInfo : public ::omnetpp::cObject
{
  protected:
    int label = -1;

  private:
    void copy(const OBS_BurstifierInfo& other);

  protected:
    bool operator==(const OBS_BurstifierInfo&) = delete;

  public:
    OBS_BurstifierInfo();
    OBS_BurstifierInfo(const OBS_BurstifierInfo& other);
    virtual ~OBS_BurstifierInfo();
    OBS_BurstifierInfo& operator=(const OBS_BurstifierInfo& other);
    virtual OBS_BurstifierInfo *dup() const override {return new OBS_BurstifierInfo(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getLabel() const;
    virtual void setLabel(int label);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OBS_BurstifierInfo& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OBS_BurstifierInfo& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline OBS_BurstifierInfo *fromAnyPtr(any_ptr ptr) { return check_and_cast<OBS_BurstifierInfo*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __OBS_BURSTIFIERINFO_M_H

