//
// Generated file, do not edit! Created by opp_msgtool 6.1 from src/CoreNode/OBS_ControlUnitInfo.msg.
//

#ifndef __OBS_CONTROLUNITINFO_M_H
#define __OBS_CONTROLUNITINFO_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class OBS_ControlUnitInfo;
/**
 * Class generated from <tt>src/CoreNode/OBS_ControlUnitInfo.msg:30</tt> by opp_msgtool.
 * <pre>
 * //
 * // Self-message used in OBS_CoreControlUnit to schedule OXC connections/disconnections.
 * //
 * // This message kind can take two values:
 * //
 * // - OBS_SCHEDULE_OXC (1)
 * // - OBS_UNSCHEDULE_OXC (2): In this case, only inGate field will be read
 * //
 * message OBS_ControlUnitInfo
 * {
 *     int inGate = -1; // OXC input gate
 *     int outGate = -1; //OXC output gate
 * }
 * </pre>
 */
class OBS_ControlUnitInfo : public ::omnetpp::cMessage
{
  protected:
    int inGate = -1;
    int outGate = -1;

  private:
    void copy(const OBS_ControlUnitInfo& other);

  protected:
    bool operator==(const OBS_ControlUnitInfo&) = delete;

  public:
    OBS_ControlUnitInfo(const char *name=nullptr, short kind=0);
    OBS_ControlUnitInfo(const OBS_ControlUnitInfo& other);
    virtual ~OBS_ControlUnitInfo();
    OBS_ControlUnitInfo& operator=(const OBS_ControlUnitInfo& other);
    virtual OBS_ControlUnitInfo *dup() const override {return new OBS_ControlUnitInfo(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getInGate() const;
    virtual void setInGate(int inGate);

    virtual int getOutGate() const;
    virtual void setOutGate(int outGate);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OBS_ControlUnitInfo& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OBS_ControlUnitInfo& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline OBS_ControlUnitInfo *fromAnyPtr(any_ptr ptr) { return check_and_cast<OBS_ControlUnitInfo*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __OBS_CONTROLUNITINFO_M_H

